#!/usr/bin/env bash
# Regenerate third-party-licenses.md from the current dependency graph.
#
# rwave ships as a standalone static binary, so a user who downloads a release
# asset never sees the repository. The permissive licences its dependencies
# carry (MIT, BSD-3-Clause, ISC, Zlib, Apache-2.0) all require the copyright
# notice to travel with a *binary* redistribution — MIT "in all copies",
# BSD-3-Clause clause 2 "in the documentation and/or other materials provided
# with the distribution". This file is that material, and release.yml uploads
# it alongside the binaries.
#
# Only cargo + python3 are needed; no cargo-about / cargo-license install.
#
# Run after any dependency change:
#   bash scripts/gen-licenses.sh && git diff --stat third-party-licenses.md
set -euo pipefail

cd "$(dirname "$0")/.."
OUT=third-party-licenses.md

# The linked set: normal (non-dev) dependencies of the rwave binary. Build-time
# proc-macro crates ride along in this list; keeping them is deliberate — an
# over-inclusive notice file is harmless, while pruning risks dropping a crate
# whose code does reach the binary.
#
# `--target all` is required, not a nicety. Without it cargo resolves for the
# host only, so the file would omit every platform-gated dependency of the other
# targets we publish (e.g. `windows-link`, reached through libloading) — the
# Windows binary would ship missing notices, and the CI drift check would flip
# with the runner's OS.
cargo tree -p rwave --edges normal --prefix none --target all 2>/dev/null \
  | sed 's/ (\*)$//' | awk 'NF {print $1 "\t" $2}' | sort -u > /tmp/_rwave_deps.tsv

cargo metadata --format-version 1 --locked > /tmp/_rwave_meta.json

python3 - "$OUT" <<'PY'
import hashlib, json, pathlib, sys, re

out_path = pathlib.Path(sys.argv[1])
meta = json.load(open("/tmp/_rwave_meta.json"))

wanted = set()
for line in open("/tmp/_rwave_deps.tsv"):
    parts = line.rstrip("\n").split("\t")
    if len(parts) == 2 and parts[0]:
        wanted.add((parts[0], parts[1].lstrip("v")))

pkgs = {}
for p in meta["packages"]:
    key = (p["name"], p["version"])
    if key in wanted:
        pkgs[key] = p

# rwave's own code is covered by ./LICENSE, not by this file.
pkgs.pop(("rwave", meta["packages"][0]["version"]), None)
pkgs = {k: v for k, v in pkgs.items() if k[0] != "rwave"}

LICENSE_FILE_RE = re.compile(r"^(LICEN[CS]E|COPYING|NOTICE)", re.I)

def license_texts(pkg):
    """Every licence file shipped next to a crate's manifest, as (name, text)."""
    root = pathlib.Path(pkg["manifest_path"]).parent
    found = []
    if not root.is_dir():
        return found
    for f in sorted(root.iterdir()):
        if f.is_file() and LICENSE_FILE_RE.match(f.name):
            try:
                txt = f.read_text(encoding="utf-8", errors="replace").strip()
            except OSError:
                continue
            if txt:
                found.append((f.name, txt))
    return found

# Group by exact licence text so the MIT body is not repeated ~25 times, while
# per-crate copyright lines (which differ, and which MIT requires be retained)
# each keep their own entry.
groups = {}
missing = []
for key in sorted(pkgs, key=lambda k: (k[0].lower(), k[1])):
    pkg = pkgs[key]
    texts = license_texts(pkg)
    if not texts:
        missing.append((key, pkg.get("license") or "?"))
        continue
    for fname, txt in texts:
        h = hashlib.sha256(txt.encode()).hexdigest()
        g = groups.setdefault(h, {"text": txt, "file": fname, "crates": set()})
        g["crates"].add(key)

lines = []
lines.append("# Third-party notices")
lines.append("")
lines.append(
    "`rwave` is distributed as a single statically linked binary. The crates "
    "listed here are compiled into it, and their licences require that the "
    "copyright notices travel with a binary redistribution. Their full texts "
    "follow."
)
lines.append("")
lines.append(
    "rwave's own code is **not** covered by this file — see [`LICENSE`](LICENSE) "
    "(MIT). Generated by `scripts/gen-licenses.sh`; do not edit by hand."
)
lines.append("")
lines.append("## Bundled crates")
lines.append("")
lines.append("| Crate | Version | Licence |")
lines.append("|---|---|---|")
for (name, ver) in sorted(pkgs, key=lambda k: (k[0].lower(), k[1])):
    lic = pkgs[(name, ver)].get("license") or "see text below"
    lines.append(f"| `{name}` | {ver} | {lic} |")
lines.append("")

if missing:
    lines.append("### Crates with no licence file in their source tree")
    lines.append("")
    lines.append(
        "The licence is declared in crate metadata; no licence file ships with "
        "the source. The SPDX expression governs."
    )
    lines.append("")
    for (name, ver), lic in missing:
        lines.append(f"- `{name}` {ver} — {lic}")
    lines.append("")

# C sources a crate compiles into the binary are invisible to the scan above:
# it walks each crate's own licence files, and an amalgamation carries its terms
# inside the .c file. SQLite is the only such case, and its terms are a
# dedication rather than a licence, so it is stated here rather than left out.
if any(name == "libsqlite3-sys" for (name, _v) in pkgs):
    lines.append("### Compiled-in C sources")
    lines.append("")
    lines.append(
        "`libsqlite3-sys` compiles the SQLite amalgamation into the binary. SQLite "
        "carries no licence file: its terms live in the source itself, and are a "
        "dedication to the public domain."
    )
    lines.append("")
    lines.append("```")
    lines.append(
        "The author disclaims copyright to this source code.  In place of\n"
        "a legal notice, here is a blessing:\n"
        "\n"
        "    May you do good and not evil.\n"
        "    May you find forgiveness for yourself and forgive others.\n"
        "    May you share freely, never taking more than you give."
    )
    lines.append("```")
    lines.append("")

lines.append("## Licence texts")
lines.append("")
for h in sorted(groups, key=lambda h: sorted(groups[h]["crates"])[0][0].lower()):
    g = groups[h]
    crates = ", ".join(f"`{n}` {v}" for n, v in sorted(g["crates"]))
    lines.append(f"### {g['file']} — applies to: {crates}")
    lines.append("")
    lines.append("```")
    lines.append(g["text"])
    lines.append("```")
    lines.append("")

out_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
print(f"wrote {out_path}: {len(pkgs)} crates, {len(groups)} distinct licence texts")
PY
